[package]
name = "mylisp"
version = "0.1.0"
authors = ["Ilya Bogdanov <fumlead@gmail.com>"]

[dependencies]
rustyline = "1.0"
regex = "0.2"

[dependencies.nom]
version = "^3.1"
features = ["verbose-errors", "regexp"]